### ISSUE TITLE
items

### ISSUE THREAD

**Issue by mariacasancho** [nthiebes/GameJam#5]
we need items that they will be on the map. Items will have different squares of length some of them will block the way or may the way slow.

There will be 2 kind of items:
- [ItemBefore] to place before the time starts: "walls, rocks, rivers,..."
- [ItemAfter] to place after the time starts: "bomb, robots, glue,.."

This item will have a property time that will be the time that the person will take to pass the square where the item is located

**Comment by nthiebes** [comment]
DONE!
